KEY_OVERRIDE_ENABLE = yes
MOUSEKEY_ENABLE = yes
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
WPM_ENABLE = yes
EXTRAKEY_ENABLE = yes

AUDIO_ENABLE = no

LTO_ENABLE = yes

UNICODE_ENABLE = no
COMMAND_ENABLE = no

CONSOLE_ENABLE = no

SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no

AVR_USE_MINIMAL_PRINTF = yes

